<a href="https://colab.research.google.com/github/sanngh/Course/blob/master/TensorFlowBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
import numpy as np

In [3]:
print("Using TensorFlow version :",tf.__version__)

Using TensorFlow version : 2.8.2


Tensor of diff ranks

In [14]:
""" Vector ia a 1-D tensor """

vector_tf  = tf.constant([0,1,2,3,4,5])
vector_np  = np.array([0,1,2,3,4,5])
print("Shape ",vector_tf.shape, vector_np.shape)



""" Matrix ia a 2-D tensor """

matirx_tf  = tf.constant([[0,1],[2,3],[4,5]])
matrix_np  = np.array([[0,1],[2,3],[4,5]])
print("Shape ",matirx_tf.shape, matrix_np.shape)



""" 3-D tensor """

t3_tf  = tf.constant([[[0,1],[2,3],[4,5]]]*4)
t3_np  = np.array([[[0,1],[2,3],[4,5]]]*4)
print("Shape ",t3_tf.shape, t3_np.shape)



""" 4-D tensor """

t4_tf  = tf.constant([[[[0,1],[2,3],[4,5]]]*4]*5)
t4_np  = np.array([[[[0,1],[2,3],[4,5]]]*4]*5)
print("Shape ",t4_tf.shape, t4_np.shape)


Shape  (6,) (6,)
Shape  (3, 2) (3, 2)
Shape  (4, 3, 2) (4, 3, 2)
Shape  (5, 4, 3, 2) (5, 4, 3, 2)


In [15]:
t3_tf

<tf.Tensor: shape=(4, 3, 2), dtype=int32, numpy=
array([[[0, 1],
        [2, 3],
        [4, 5]],

       [[0, 1],
        [2, 3],
        [4, 5]],

       [[0, 1],
        [2, 3],
        [4, 5]],

       [[0, 1],
        [2, 3],
        [4, 5]]], dtype=int32)>

In [16]:
print(t3_tf)

tf.Tensor(
[[[0 1]
  [2 3]
  [4 5]]

 [[0 1]
  [2 3]
  [4 5]]

 [[0 1]
  [2 3]
  [4 5]]

 [[0 1]
  [2 3]
  [4 5]]], shape=(4, 3, 2), dtype=int32)


Declaring Tensor

In [17]:
const_tf = tf.constant([[1,2],[3,4]])

In [18]:
varia_tf = tf.Variable([[1,2],[3,4]])

In [22]:
""" int32 declare"""

varia_tf_int32 = tf.Variable([[1,2],[3,4]], dtype = tf.int32)

varia_tf_in64 = tf.Variable([[1,2],[3,4]], dtype = tf.int64)

varia_tf_bool = tf.Variable([True,False,True], dtype = tf.bool)

In [25]:
print(varia_tf_int32)
print(varia_tf_in64)
print(varia_tf_bool)


print(varia_tf_int32.numpy())
print(varia_tf_in64.numpy())
print(varia_tf_bool.numpy())

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2, 2) dtype=int64, numpy=
array([[1, 2],
       [3, 4]])>
<tf.Variable 'Variable:0' shape=(3,) dtype=bool, numpy=array([ True, False,  True])>
[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
[ True False  True]


Declare Tensor 2,2,2,2 shape with random number from normal distribution with mean 1 and SD as 1

In [30]:
arr = np.random.randn(2,2,2,2)
print(arr.shape)
print(arr)

(2, 2, 2, 2)
[[[[-1.00052991  0.31250366]
   [-0.83042453 -0.72594936]]

  [[-1.32795863 -0.75179424]
   [-1.10585295  0.79656794]]]


 [[[-0.05676252 -0.31230726]
   [-1.66609124 -0.16467187]]

  [[-0.54213159 -0.04643955]
   [ 0.04653103 -0.39805297]]]]


In [33]:
arr_tf = tf.constant(arr)
print(arr_tf)
print(arr_tf.numpy())

tf.Tensor(
[[[[-1.00052991  0.31250366]
   [-0.83042453 -0.72594936]]

  [[-1.32795863 -0.75179424]
   [-1.10585295  0.79656794]]]


 [[[-0.05676252 -0.31230726]
   [-1.66609124 -0.16467187]]

  [[-0.54213159 -0.04643955]
   [ 0.04653103 -0.39805297]]]], shape=(2, 2, 2, 2), dtype=float64)
[[[[-1.00052991  0.31250366]
   [-0.83042453 -0.72594936]]

  [[-1.32795863 -0.75179424]
   [-1.10585295  0.79656794]]]


 [[[-0.05676252 -0.31230726]
   [-1.66609124 -0.16467187]]

  [[-0.54213159 -0.04643955]
   [ 0.04653103 -0.39805297]]]]
