<a href="https://colab.research.google.com/github/sanngh/Course/blob/master/TensorFlowBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
import numpy as np

In [3]:
print("Using TensorFlow version :",tf.__version__)

Using TensorFlow version : 2.8.2


Tensor of diff ranks

In [4]:
""" Vector ia a 1-D tensor """

vector_tf  = tf.constant([0,1,2,3,4,5])
vector_np  = np.array([0,1,2,3,4,5])
print("Shape ",vector_tf.shape, vector_np.shape)



""" Matrix ia a 2-D tensor """

matirx_tf  = tf.constant([[0,1],[2,3],[4,5]])
matrix_np  = np.array([[0,1],[2,3],[4,5]])
print("Shape ",matirx_tf.shape, matrix_np.shape)



""" 3-D tensor """

t3_tf  = tf.constant([[[0,1],[2,3],[4,5]]]*4)
t3_np  = np.array([[[0,1],[2,3],[4,5]]]*4)
print("Shape ",t3_tf.shape, t3_np.shape)



""" 4-D tensor """

t4_tf  = tf.constant([[[[0,1],[2,3],[4,5]]]*4]*5)
t4_np  = np.array([[[[0,1],[2,3],[4,5]]]*4]*5)
print("Shape ",t4_tf.shape, t4_np.shape)


Shape  (6,) (6,)
Shape  (3, 2) (3, 2)
Shape  (4, 3, 2) (4, 3, 2)
Shape  (5, 4, 3, 2) (5, 4, 3, 2)


In [5]:
t3_tf

<tf.Tensor: shape=(4, 3, 2), dtype=int32, numpy=
array([[[0, 1],
        [2, 3],
        [4, 5]],

       [[0, 1],
        [2, 3],
        [4, 5]],

       [[0, 1],
        [2, 3],
        [4, 5]],

       [[0, 1],
        [2, 3],
        [4, 5]]], dtype=int32)>

In [6]:
print(t3_tf)

tf.Tensor(
[[[0 1]
  [2 3]
  [4 5]]

 [[0 1]
  [2 3]
  [4 5]]

 [[0 1]
  [2 3]
  [4 5]]

 [[0 1]
  [2 3]
  [4 5]]], shape=(4, 3, 2), dtype=int32)


Declaring Tensor

In [7]:
const_tf = tf.constant([[1,2],[3,4]])

In [8]:
varia_tf = tf.Variable([[1,2],[3,4]])

In [9]:
""" int32 declare"""

varia_tf_int32 = tf.Variable([[1,2],[3,4]], dtype = tf.int32)

varia_tf_in64 = tf.Variable([[1,2],[3,4]], dtype = tf.int64)

varia_tf_bool = tf.Variable([True,False,True], dtype = tf.bool)

In [10]:
print(varia_tf_int32)
print(varia_tf_in64)
print(varia_tf_bool)


print(varia_tf_int32.numpy())
print(varia_tf_in64.numpy())
print(varia_tf_bool.numpy())

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2, 2) dtype=int64, numpy=
array([[1, 2],
       [3, 4]])>
<tf.Variable 'Variable:0' shape=(3,) dtype=bool, numpy=array([ True, False,  True])>
[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
[ True False  True]


Declare Tensor 2,2,2,2 shape with random number from normal distribution with mean 1 and SD as 1

In [18]:
# Approach 1
arr = np.random.randn(2,2,2,2)
arr = arr + 1 ### ==> for mean 1
arr = (1 * arr  ) + 1 ### ==> for SD as 1
print(arr.shape)
print(arr)

(2, 2, 2, 2)
[[[[ 0.55945206  0.92923184]
   [ 3.10559956  2.41583322]]

  [[ 1.55214199  1.97179742]
   [ 2.33771167  0.99805524]]]


 [[[ 1.23712     1.64965819]
   [ 2.20681786  2.12807214]]

  [[ 0.30366813  2.20197971]
   [-0.28698497  2.29285507]]]]


In [19]:
arr_tf = tf.constant(arr)
print(arr_tf)
print(arr_tf.numpy())

tf.Tensor(
[[[[ 0.55945206  0.92923184]
   [ 3.10559956  2.41583322]]

  [[ 1.55214199  1.97179742]
   [ 2.33771167  0.99805524]]]


 [[[ 1.23712     1.64965819]
   [ 2.20681786  2.12807214]]

  [[ 0.30366813  2.20197971]
   [-0.28698497  2.29285507]]]], shape=(2, 2, 2, 2), dtype=float64)
[[[[ 0.55945206  0.92923184]
   [ 3.10559956  2.41583322]]

  [[ 1.55214199  1.97179742]
   [ 2.33771167  0.99805524]]]


 [[[ 1.23712     1.64965819]
   [ 2.20681786  2.12807214]]

  [[ 0.30366813  2.20197971]
   [-0.28698497  2.29285507]]]]


In [21]:
# Approach 2
# Using TF functions 
arr_tf = tf.random.normal((2,2,2,2),mean = 1, stddev  =1 )
print(arr_tf.numpy())

[[[[ 1.4027361   0.860129  ]
   [ 1.2550468   0.27226186]]

  [[ 2.6277952   1.7042601 ]
   [ 3.4524858   1.9667721 ]]]


 [[[ 2.0062752   2.0579472 ]
   [ 0.9220606   1.138672  ]]

  [[ 0.58462083 -0.00626159]
   [ 2.5296717   3.084261  ]]]]


In [25]:
# Maths Operation

const_tf = tf.constant([[0,1],[2,3],[4,5]])

new_tf = tf.add(const_tf,1)
print(new_tf)

new_tf = tf.add(const_tf,-1)
print(new_tf)

new_tf = tf.multiply(const_tf,100)
print(new_tf)


tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[-1  0]
 [ 1  2]
 [ 3  4]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[  0 100]
 [200 300]
 [400 500]], shape=(3, 2), dtype=int32)


In [28]:
x = tf.Variable([list(range(5))]*5)
y = tf.Variable([list(range(5,10))]*5)

print(x)
print(y)

<tf.Variable 'Variable:0' shape=(5, 5) dtype=int32, numpy=
array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]], dtype=int32)>
<tf.Variable 'Variable:0' shape=(5, 5) dtype=int32, numpy=
array([[5, 6, 7, 8, 9],
       [5, 6, 7, 8, 9],
       [5, 6, 7, 8, 9],
       [5, 6, 7, 8, 9],
       [5, 6, 7, 8, 9]], dtype=int32)>


In [31]:
z=x+y
print(z)

tf.Tensor(
[[ 5  7  9 11 13]
 [ 5  7  9 11 13]
 [ 5  7  9 11 13]
 [ 5  7  9 11 13]
 [ 5  7  9 11 13]], shape=(5, 5), dtype=int32)


In [32]:
z=x.numpy()+y.numpy()
print(z)

[[ 5  7  9 11 13]
 [ 5  7  9 11 13]
 [ 5  7  9 11 13]
 [ 5  7  9 11 13]
 [ 5  7  9 11 13]]


In [37]:
x = tf.random.uniform((2,2),minval = 1, maxval = 10 , dtype= tf.int32)

In [38]:
print(x.numpy())


[[9 7]
 [1 8]]


In [40]:
y = tf.pow(x,2)
print(y.numpy())

[[81 49]
 [ 1 64]]


In [41]:
y = x*x
print(y.numpy())

[[81 49]
 [ 1 64]]


In [44]:
x = tf.random.uniform((2,2),minval = 1, maxval = 10)
print(x)

tf.Tensor(
[[7.3196898 9.829077 ]
 [3.9226904 9.664576 ]], shape=(2, 2), dtype=float32)


In [45]:
y = tf.pow(x,2)
print(y.numpy())

[[53.577858 96.61075 ]
 [15.3875   93.40402 ]]


In [47]:
x = tf.random.uniform((2,2),minval = 1, maxval = 10 , dtype= tf.int32)
print(x)

tf.Tensor(
[[5 2]
 [9 6]], shape=(2, 2), dtype=int32)


In [48]:
y = tf.multiply(x,x)
print(y.numpy())

[[25  4]
 [81 36]]


In [52]:
x = tf.random.uniform((1,3),minval = 1, maxval = 10 , dtype= tf.int32)
y = tf.random.uniform((1,3),minval = 1, maxval = 10 , dtype= tf.int32)

print(x)
print(y)

tf.Tensor([[7 6 6]], shape=(1, 3), dtype=int32)
tf.Tensor([[1 5 1]], shape=(1, 3), dtype=int32)


In [53]:
z = x+y
print(z)

tf.Tensor([[ 8 11  7]], shape=(1, 3), dtype=int32)
