<a href="https://colab.research.google.com/github/sanngh/Course/blob/master/TensorFlowBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
import numpy as np

In [3]:
print("Using TensorFlow version :",tf.__version__)

Using TensorFlow version : 2.8.2


Tensor of diff ranks

In [4]:
""" Vector ia a 1-D tensor """

vector_tf  = tf.constant([0,1,2,3,4,5])
vector_np  = np.array([0,1,2,3,4,5])
print("Shape ",vector_tf.shape, vector_np.shape)



""" Matrix ia a 2-D tensor """

matirx_tf  = tf.constant([[0,1],[2,3],[4,5]])
matrix_np  = np.array([[0,1],[2,3],[4,5]])
print("Shape ",matirx_tf.shape, matrix_np.shape)



""" 3-D tensor """

t3_tf  = tf.constant([[[0,1],[2,3],[4,5]]]*4)
t3_np  = np.array([[[0,1],[2,3],[4,5]]]*4)
print("Shape ",t3_tf.shape, t3_np.shape)



""" 4-D tensor """

t4_tf  = tf.constant([[[[0,1],[2,3],[4,5]]]*4]*5)
t4_np  = np.array([[[[0,1],[2,3],[4,5]]]*4]*5)
print("Shape ",t4_tf.shape, t4_np.shape)


Shape  (6,) (6,)
Shape  (3, 2) (3, 2)
Shape  (4, 3, 2) (4, 3, 2)
Shape  (5, 4, 3, 2) (5, 4, 3, 2)


In [5]:
t3_tf

<tf.Tensor: shape=(4, 3, 2), dtype=int32, numpy=
array([[[0, 1],
        [2, 3],
        [4, 5]],

       [[0, 1],
        [2, 3],
        [4, 5]],

       [[0, 1],
        [2, 3],
        [4, 5]],

       [[0, 1],
        [2, 3],
        [4, 5]]], dtype=int32)>

In [6]:
print(t3_tf)

tf.Tensor(
[[[0 1]
  [2 3]
  [4 5]]

 [[0 1]
  [2 3]
  [4 5]]

 [[0 1]
  [2 3]
  [4 5]]

 [[0 1]
  [2 3]
  [4 5]]], shape=(4, 3, 2), dtype=int32)


Declaring Tensor

In [7]:
const_tf = tf.constant([[1,2],[3,4]])

In [8]:
varia_tf = tf.Variable([[1,2],[3,4]])

In [9]:
""" int32 declare"""

varia_tf_int32 = tf.Variable([[1,2],[3,4]], dtype = tf.int32)

varia_tf_in64 = tf.Variable([[1,2],[3,4]], dtype = tf.int64)

varia_tf_bool = tf.Variable([True,False,True], dtype = tf.bool)

In [10]:
print(varia_tf_int32)
print(varia_tf_in64)
print(varia_tf_bool)


print(varia_tf_int32.numpy())
print(varia_tf_in64.numpy())
print(varia_tf_bool.numpy())

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2, 2) dtype=int64, numpy=
array([[1, 2],
       [3, 4]])>
<tf.Variable 'Variable:0' shape=(3,) dtype=bool, numpy=array([ True, False,  True])>
[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
[ True False  True]


Declare Tensor 2,2,2,2 shape with random number from normal distribution with mean 1 and SD as 1

In [18]:
# Approach 1
arr = np.random.randn(2,2,2,2)
arr = arr + 1 ### ==> for mean 1
arr = (1 * arr  ) + 1 ### ==> for SD as 1
print(arr.shape)
print(arr)

(2, 2, 2, 2)
[[[[ 0.55945206  0.92923184]
   [ 3.10559956  2.41583322]]

  [[ 1.55214199  1.97179742]
   [ 2.33771167  0.99805524]]]


 [[[ 1.23712     1.64965819]
   [ 2.20681786  2.12807214]]

  [[ 0.30366813  2.20197971]
   [-0.28698497  2.29285507]]]]


In [19]:
arr_tf = tf.constant(arr)
print(arr_tf)
print(arr_tf.numpy())

tf.Tensor(
[[[[ 0.55945206  0.92923184]
   [ 3.10559956  2.41583322]]

  [[ 1.55214199  1.97179742]
   [ 2.33771167  0.99805524]]]


 [[[ 1.23712     1.64965819]
   [ 2.20681786  2.12807214]]

  [[ 0.30366813  2.20197971]
   [-0.28698497  2.29285507]]]], shape=(2, 2, 2, 2), dtype=float64)
[[[[ 0.55945206  0.92923184]
   [ 3.10559956  2.41583322]]

  [[ 1.55214199  1.97179742]
   [ 2.33771167  0.99805524]]]


 [[[ 1.23712     1.64965819]
   [ 2.20681786  2.12807214]]

  [[ 0.30366813  2.20197971]
   [-0.28698497  2.29285507]]]]


In [21]:
# Approach 2
# Using TF functions 
arr_tf = tf.random.normal((2,2,2,2),mean = 1, stddev  =1 )
print(arr_tf.numpy())

[[[[ 1.4027361   0.860129  ]
   [ 1.2550468   0.27226186]]

  [[ 2.6277952   1.7042601 ]
   [ 3.4524858   1.9667721 ]]]


 [[[ 2.0062752   2.0579472 ]
   [ 0.9220606   1.138672  ]]

  [[ 0.58462083 -0.00626159]
   [ 2.5296717   3.084261  ]]]]
